//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 07:34:05 PM CET 
//


package ch.so.geo.schema.agi.landregisterparceldescription.extract;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.so.geo.schema.agi.landregisterparceldescription.extract package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetExtractByXY_QNAME = new QName("http://geo.so.ch/schema/AGI/LandRegisterParcelDescription/Extract", "GetExtractByXY");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.so.geo.schema.agi.landregisterparceldescription.extract
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetExtractByXYResponseType }
     * 
     */
    public GetExtractByXYResponseType createGetExtractByXYResponseType() {
        return new GetExtractByXYResponseType();
    }

    /**
     * Create an instance of {@link Office }
     * 
     */
    public Office createOffice() {
        return new Office();
    }

    /**
     * Create an instance of {@link RealEstateDPR }
     * 
     */
    public RealEstateDPR createRealEstateDPR() {
        return new RealEstateDPR();
    }

    /**
     * Create an instance of {@link Extract }
     * 
     */
    public Extract createExtract() {
        return new Extract();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetExtractByXYResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://geo.so.ch/schema/AGI/LandRegisterParcelDescription/Extract", name = "GetExtractByXY")
    public JAXBElement<GetExtractByXYResponseType> createGetExtractByXY(GetExtractByXYResponseType value) {
        return new JAXBElement<GetExtractByXYResponseType>(_GetExtractByXY_QNAME, GetExtractByXYResponseType.class, null, value);
    }

}
