//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 07:34:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://geo.so.ch/schema/AGI/LandRegisterParcelDescription/Extract", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.so.geo.schema.agi.landregisterparceldescription.extract;
