//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 07:48:34 PM CET 
//


package ch.so.geo.schema.agi.landregisterparceldescription._1_0.extract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Extract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Extract">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CantonalLogo" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="Office" type="{http://geo.so.ch/schema/AGI/LandRegisterParcelDescription/1.0/Extract}Office"/>
 *         &lt;element name="RealEstate" type="{http://geo.so.ch/schema/AGI/LandRegisterParcelDescription/1.0/Extract}RealEstate_DPR"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Extract", propOrder = {
    "cantonalLogo",
    "office",
    "realEstate"
})
public class Extract {

    @XmlElement(name = "CantonalLogo")
    protected byte[] cantonalLogo;
    @XmlElement(name = "Office", required = true)
    protected Office office;
    @XmlElement(name = "RealEstate", required = true)
    protected RealEstateDPR realEstate;

    /**
     * Gets the value of the cantonalLogo property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCantonalLogo() {
        return cantonalLogo;
    }

    /**
     * Sets the value of the cantonalLogo property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCantonalLogo(byte[] value) {
        this.cantonalLogo = value;
    }

    /**
     * Gets the value of the office property.
     * 
     * @return
     *     possible object is
     *     {@link Office }
     *     
     */
    public Office getOffice() {
        return office;
    }

    /**
     * Sets the value of the office property.
     * 
     * @param value
     *     allowed object is
     *     {@link Office }
     *     
     */
    public void setOffice(Office value) {
        this.office = value;
    }

    /**
     * Gets the value of the realEstate property.
     * 
     * @return
     *     possible object is
     *     {@link RealEstateDPR }
     *     
     */
    public RealEstateDPR getRealEstate() {
        return realEstate;
    }

    /**
     * Sets the value of the realEstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealEstateDPR }
     *     
     */
    public void setRealEstate(RealEstateDPR value) {
        this.realEstate = value;
    }

}
